services:
  reticulum-meshchat:
    container_name: reticulum-meshchat
    image: ghcr.io/liamcottle/reticulum-meshchat:latest
    pull_policy: always
    restart: unless-stopped
    # Make the meshchat web interface accessible from the host on port 8000
    ports:
      - 0.0.0.0:8000:8000
    volumes:
      meshchat-config:/config
    # Uncomment if you have a USB device connected, such as an RNode
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0

volumes:
    meshchat-config:
